=== TheGoodSpirit/BCA---3rd-SEM/WebTech/XML/NewXml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT college (student+,name+,firstName+,lastName+,contact+,email+,address+) >
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== TheGoodSpirit/BCA---3rd-SEM/WebTech/XML/NewXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE college SYSTEM "NewXml.dtd">
<college xmlns:c9 = "https://example.com.np" xmlns:c10 = "https://example.com.np">
    <name> Butwal Kalika Campus </name>
    <address> Butwal-11, Ramnagar, Rupandehi</address>
    <c9:student>
        <firstName> Manish </firstName>
        <lastName> Ghimire </lastName>
        <contact> 9800000000 </contact>
        <email> manishghimire@gmail.com </email>
        <address> Devinagar </address>
    </c9:student>

    <c10:student>
        <firstName> Manish </firstName>
        <lastName> Ghimire </lastName>
        <contact> 9800000000 </contact>
        <email> manishghimire@gmail.com </email>
        <address> Devinagar </address>
    </c10:student>

</college>
